kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-lb
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: epmd
    protocol: TCP
    port: 4369
    targetPort: 4369
  - name: ampq
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 25672
  type: ClusterIP
