---
all:
    vars:
        ansible_user: "ubuntu"
    children:
        database:
            hosts:
                54.83.163.100:
                    db_users:
                        - { db_user: "artifactory", db_password: "{{ lookup('env', 'artifactory_password') }}" }
                    dbs:
                        - { db_name: "artifactory", db_owner: "artifactory" }
        primary:
            hosts:
                54.165.47.191:
                    artifactory_version: 7.4.1
                    artifactory_is_primary: true
                    artifactory_license_file: "{{ lookup('env', 'artifactory_license_file') }}"
                    db_download_url: "https://jdbc.postgresql.org/download/postgresql-42.2.12.jar"
                    db_type: "postgresql"
                    db_driver: "org.postgresql.Driver"
                    db_url: "jdbc:postgresql://10.0.0.219:5432/artifactory"
                    db_user: "artifactory"
                    db_password: "{{ lookup('env', 'artifactory_password') }}"
                    server_name: "ec2-54-165-47-191.compute-1.amazonaws.com"
