apiVersion: charts.helm.k8s.io/v1alpha1
kind: OpenshiftXray
metadata:
  name: openshiftxray
spec:
  xray:
    analysis:
      image:
        repository: registry.connect.redhat.com/jfrog/xray-analysis
        version: 3.3.0
      name: xray-analysis
      podManagementPolicy: Parallel
      preStartCommand: null
      updateStrategy: RollingUpdate
    database:
      password: OVERRIDE
      url: OVERRIDE
      user: OVERRIDE
    global:
      postgresqlTlsSecret: null
    indexer:
      image:
        repository: registry.connect.redhat.com/jfrog/xray-indexer
        version: 3.3.0
      name: xray-indexer
      podManagementPolicy: Parallel
      updateStrategy: RollingUpdate
    persist:
      image:
        repository: registry.connect.redhat.com/jfrog/xray-persist
        version: 3.3.0
      name: xray-persist
      persistence:
        size: 10Gi
      podManagementPolicy: Parallel
      preStartCommand: null
      updateStrategy: RollingUpdate
    postgresql:
      enabled: false
    rabbitmq-ha:
      enabled: true
      image:
        repository: registry.connect.redhat.com/jfrog/xray-rabbitmq
        tag: 3.8.0
      rabbitmqEpmdPort: 4369
      rabbitmqManagerPort: 15672
      rabbitmqNodePort: 5672
      replicaCount: 1
    replicaCount: 1
    router:
      image:
        imagePullPolicy: IfNotPresent
        repository: registry.connect.redhat.com/jfrog/xray-router
        version: 1.2.1
      name: router
    server:
      image:
        repository: registry.connect.redhat.com/jfrog/xray-server
        version: 3.3.0
      name: xray-server
      podManagementPolicy: Parallel
      replicaCount: 1
      updateStrategy: RollingUpdate
    xray:
      consoleLog: false
      jfrogUrl: OVERRIDE
      joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
      masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
