---
- hosts: database
  collections:
    - jfrog.installers
  roles:
    - postgres

- hosts: primary:secondary
  collections:
    - jfrog.installers
  roles:
    - artifactory
    - artifactory_nginx_ssl
